In [1]:
import numpy as np

In [2]:
# Create an array
arr=np.array([1,2,3,4,5])

In [3]:
arr

array([1, 2, 3, 4, 5])

In [7]:
# Create a zero dimension array
arrzero=np.array(80)

In [8]:
# Checking the dimension of array
arr.ndim

1

In [9]:
arrzero.ndim

0

In [16]:
# Creating 2D array
arr1=np.array([[1,2,3,4],[5,6,7,8]])

In [17]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
arr1.ndim

2

In [19]:
# Find row and coluns of an arraay
arr1.shape

(2, 4)

In [20]:
#Checking the number of elements in array
arr1.size

8

In [21]:
# Checking the memory of an array
arr1.nbytes

32

In [22]:
arr1.dtype

dtype('int32')

In [23]:
arr1[0,2]

3

In [24]:
arr1[1,:]

array([5, 6, 7, 8])

In [25]:
arr1[0,:]

array([1, 2, 3, 4])

In [27]:
arr1[:,1]

array([2, 6])

In [34]:
arr3=np.array([1,2,3,4,5,6,7,8,9,10])

In [35]:
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr3[0:5]                         #inclusive operation

array([1, 2, 3, 4, 5])

In [39]:
arr3[5:]                           # exclusive operation

array([ 6,  7,  8,  9, 10])

In [40]:
# Zero matrix
np.zeros((4,6))                     # using in data manipulation 

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [45]:
r=np.zeros((4,6))  
r.ndim                                 # Dimensions of matrix

2

In [42]:
# Ones matrix
np.ones((5,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [43]:
np.ones((6,3,3))                      # 3D matrix

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [44]:
np.ones((6,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [46]:
np.full((40,40),560)          # For random numbers

array([[560, 560, 560, ..., 560, 560, 560],
       [560, 560, 560, ..., 560, 560, 560],
       [560, 560, 560, ..., 560, 560, 560],
       ...,
       [560, 560, 560, ..., 560, 560, 560],
       [560, 560, 560, ..., 560, 560, 560],
       [560, 560, 560, ..., 560, 560, 560]])

In [47]:
from numpy import random

In [49]:
np.random.randint(100)

73

In [52]:
np.random.rand(4,4)

array([[0.5113997 , 0.05600691, 0.32038744, 0.324975  ],
       [0.09320095, 0.015116  , 0.63793549, 0.40926693],
       [0.36894187, 0.79745611, 0.42055166, 0.65168391],
       [0.56590128, 0.11329225, 0.20746124, 0.56132966]])

In [55]:
# Identity matrix
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [56]:
# Mathematical operation of an array
arrm=np.array([4,5,7,9,45])
arrm

array([ 4,  5,  7,  9, 45])

In [57]:
print(arrm)

[ 4  5  7  9 45]


In [58]:
y=arrm+15
print(y)

[19 20 22 24 60]


In [60]:
z=arrm-40
print(z)

[-36 -35 -33 -31   5]


In [64]:
y1=arrm+100
y1
# print(y1)

array([104, 105, 107, 109, 145])

In [65]:
# multiplication operation
z1=arrm*10
z1

array([ 40,  50,  70,  90, 450])

In [66]:
print(z1)

[ 40  50  70  90 450]


In [67]:
y1*200

array([20800, 21000, 21400, 21800, 29000])

In [69]:
# Division operation
y1/7

array([14.85714286, 15.        , 15.28571429, 15.57142857, 20.71428571])

In [70]:
z1/4

array([ 10. ,  12.5,  17.5,  22.5, 112.5])

In [71]:
a1=np.array([4,6,7,3,56])
a2=np.array([46,86,23,5,9])
a1+a2

array([50, 92, 30,  8, 65])

In [72]:
print(a1+a2)

[50 92 30  8 65]


In [73]:
# cos function in an array
np.cos(a1)

array([-0.65364362,  0.96017029,  0.75390225, -0.9899925 ,  0.85322011])

In [74]:
np.cos(z1)

array([-0.66693806,  0.96496603,  0.6333192 , -0.44807362, -0.73015296])

In [80]:
arr5=np.array([[2,3,5,7,8],[5,2,9,5,1]])

In [81]:
arr5

array([[2, 3, 5, 7, 8],
       [5, 2, 9, 5, 1]])

In [82]:
print(arr5)             # matrix form

[[2 3 5 7 8]
 [5 2 9 5 1]]


In [83]:
# minimum value from an array
np.min(arr5)

1

In [86]:
# maximum value from an array
np.max(arr5)

9

In [88]:
# sum of all elements of an array
np.sum(arr5)

47

In [89]:
# iterating in 1-D
for x in a1:
    print(x)

4
6
7
3
56


In [92]:
# iterating in 2-D array
for y in  arr5:
    print(y)

[2 3 5 7 8]
[5 2 9 5 1]


In [98]:
for y1 in arr5:
    for y2 in y1:
        print(y2)

2
3
5
7
8
5
2
9
5
1


In [104]:
r=np.array([[[34,5,6,8,10],[35,67,3,5,9]],[[24,64,23,12,45],[3,5,45,78,23]]])

In [105]:
r

array([[[34,  5,  6,  8, 10],
        [35, 67,  3,  5,  9]],

       [[24, 64, 23, 12, 45],
        [ 3,  5, 45, 78, 23]]])

In [106]:
print(r)

[[[34  5  6  8 10]
  [35 67  3  5  9]]

 [[24 64 23 12 45]
  [ 3  5 45 78 23]]]


In [107]:
# iterating in 3-D array
for w in r:
    print(r)

[[[34  5  6  8 10]
  [35 67  3  5  9]]

 [[24 64 23 12 45]
  [ 3  5 45 78 23]]]
[[[34  5  6  8 10]
  [35 67  3  5  9]]

 [[24 64 23 12 45]
  [ 3  5 45 78 23]]]


In [108]:
for w1 in r:
    for w2 in w1:
        for w3 in w2:
            print(w3)

34
5
6
8
10
35
67
3
5
9
24
64
23
12
45
3
5
45
78
23


In [100]:
random.randint(100)                           # Generatin random value

48

In [103]:
# copying of an array
ar1=arr5.copy()
print(ar1)

[[2 3 5 7 8]
 [5 2 9 5 1]]
